<?
$aMenuLinks = array(
    array(
        "Услуги",
        "/services/",
        array(),
        array(),
        ""
    ),
    array(
        "О клинике",
        "/about/",
        array(),
        array(),
        ""
    ),
    array(
        "Вакансии клиники",
        "/about/jobs/",
        array(),
        array(),
        ""
    ),
    array(
        "Юридические документы",
        "/about/legal-docs/",
        array(),
        array(),
        ""
    ),
    array(
        "Лицензии",
        "/about/licenses/",
        array(),
        array(),
        ""
    ),
    array(
        "Вопросы и ответы",
        "/about/faq/",
        array(),
        array(),
        ""
    ),
    array(
        "Специалисты",
        "/doctors/",
        array(),
        array(),
        ""
    ),
    array(
        "Статьи",
        "/articles/",
        array(),
        array(),
        ""
    ),
    array(
        "Отзывы",
        "/reviews/",
        array(),
        array(),
        ""
    ),
    array(
        "Акции",
        "/stocks/",
        array(),
        array(),
        ""
    ),
    array(
        "Контакты",
        "/contacts/",
        array(),
        array(),
        ""
    )
);
